package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.ProductCategory;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    ProductCategory selectByPrimaryKey(BigDecimal productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKey(ProductCategory record);
}