package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.ProductSize;

public interface ProductSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal productSizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    int insert(ProductSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    int insertSelective(ProductSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    ProductSize selectByPrimaryKey(BigDecimal productSizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    int updateByPrimaryKeySelective(ProductSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    int updateByPrimaryKey(ProductSize record);
}