package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.StoreCategory;

public interface StoreCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal storeCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insert(StoreCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insertSelective(StoreCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    StoreCategory selectByPrimaryKey(BigDecimal storeCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKeySelective(StoreCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CATEGORY
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKey(StoreCategory record);
}