package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.Store;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insertSelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    Store selectByPrimaryKey(BigDecimal storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKeySelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKey(Store record);
}