package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.StoreAuth;

public interface StoreAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal storeAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insert(StoreAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insertSelective(StoreAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    StoreAuth selectByPrimaryKey(BigDecimal storeAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKeySelective(StoreAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKey(StoreAuth record);
}