package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.TyOrderDetail;

public interface TyOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal orderDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    int insert(TyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    int insertSelective(TyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    TyOrderDetail selectByPrimaryKey(BigDecimal orderDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    int updateByPrimaryKeySelective(TyOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    int updateByPrimaryKey(TyOrderDetail record);
}