package tw.com.imsoft.dao.mapper;

import java.math.BigDecimal;
import tw.com.imsoft.dao.model.TyOrder;

public interface TyOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int deleteByPrimaryKey(BigDecimal orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insert(TyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int insertSelective(TyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    TyOrder selectByPrimaryKey(BigDecimal orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKeySelective(TyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TY_ORDER
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    int updateByPrimaryKey(TyOrder record);
}