package tw.com.imsoft.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.STORE_ID
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_DESC
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_IMG
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private String productImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_SIZE_ID
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal productSizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_CATEGORY_ID
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private static final long serialVersionUID = 1L;
}