package tw.com.imsoft.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ProductSize implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SIZE.PRODUCT_SIZE_ID
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    private BigDecimal productSizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SIZE.PRODUCT_ID
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    private BigDecimal productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SIZE.PRODUCT_SIZE_NAME
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    private String productSizeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SIZE.PRICE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_SIZE
     *
     * @mbg.generated Wed Mar 15 15:25:37 CST 2023
     */
    private static final long serialVersionUID = 1L;
}