package tw.com.imsoft.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class StoreAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_AUTH.STORE_AUTH_ID
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    private BigDecimal storeAuthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_AUTH.STORE_ID
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    private BigDecimal storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_AUTH.USERNAME
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_AUTH.PASSWORD
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STORE_AUTH
     *
     * @mbg.generated Mon Mar 06 15:47:11 CST 2023
     */
    private static final long serialVersionUID = 1L;
}