package tw.com.imsoft.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TyOrderDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TY_ORDER_DETAIL.ORDER_DETAIL_NO
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal orderDetailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TY_ORDER_DETAIL.ORDER_NO
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TY_ORDER_DETAIL.PRODUCT_SIZE_ID
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal productSizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TY_ORDER_DETAIL.REMARK
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TY_ORDER_DETAIL.NUM
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TY_ORDER_DETAIL.SUM
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private BigDecimal sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TY_ORDER_DETAIL
     *
     * @mbg.generated Wed Mar 15 15:35:45 CST 2023
     */
    private static final long serialVersionUID = 1L;
}